"""Carta T²MRCD: la carta por defecto, con MRCD como estimador (``docs/metodos/t2mrcd.md``).

Solo importa ``domain.common`` y ``domain.estimators.mrcd`` (contratos de import-linter).
"""

from voracious.domain.charts.t2mrcd.aggregation import (
    MC_ERROR_RESAMPLES,
    QUANTILE_METHOD,
    PooledQuantile,
    pooled_quantile,
)
from voracious.domain.charts.t2mrcd.bootstrap import (
    BOOTSTRAP_LIMIT_NOT_FINITE,
    BOOTSTRAP_REPLICATE_FAILED,
    BootstrapLimits,
    ReplicateContext,
    ReplicateFailure,
    ReplicateOutcome,
    ReplicateTask,
    calibrate_limits,
    replicate_tasks,
    run_replicate,
)
from voracious.domain.charts.t2mrcd.chart import (
    BASE_CONSISTENCY_RTOL,
    CHART_ID,
    STATISTIC_REFERENCE,
    T2MRCD_CLEAN_CRITERION_INVALID,
    T2MRCD_DECISION_PENDING,
    T2MRCD_NO_CLEAN_OBSERVATIONS,
    T2MRCDChart,
)
from voracious.domain.charts.t2mrcd.clean import best_subset_criterion
from voracious.domain.charts.t2mrcd.codec import (
    MODEL_FORMAT_VERSION,
    REPORT_FORMAT_VERSION,
    decode_comparison,
    decode_limits,
    decode_model,
    decode_report,
    encode_comparison,
    encode_limits,
    encode_model,
    encode_report,
)
from voracious.domain.charts.t2mrcd.comparison import (
    AnyFormalTestChangeRule,
    ChangeTestResult,
    ComparisonResult,
    CovarianceChangeTest,
    DecisionRule,
    FrobeniusRelativeChange,
    MeanChangeTest,
    RelativeChangeMetric,
    any_formal_test_change,
    compare_bases,
    frobenius_relative_change,
)
from voracious.domain.charts.t2mrcd.model import LimitRegime, T2MRCDModel, T2MRCDMonitoring
from voracious.domain.charts.t2mrcd.params import (
    DEFAULT_ALPHA_LIMIT,
    DEFAULT_N_REPLICATES,
    DEFAULT_PHASE2_ALPHA_LIMIT,
    T2MRCD_MRCD_ALPHA,
    CleanCriterion,
    LimitAggregation,
    T2MRCDBootstrap,
    T2MRCDParams,
)
from voracious.domain.charts.t2mrcd.phase1 import (
    Aggregations,
    Phase1Stage,
    calibrate_stage,
    fit_base,
    fit_base_mrcd,
    fit_stage,
)
from voracious.domain.charts.t2mrcd.phase2_limit import (
    BOOTSTRAP_OOB_EMPTY,
    BootstrapOOBSampler,
    ReplicateSampler,
    bootstrap_oob_sampler,
)
from voracious.domain.charts.t2mrcd.registry import (
    BEST_SUBSET_CRITERION_NAME,
    DEFAULT_STRATEGIES,
    T2MRCDStrategies,
    decode_mrcd_params,
    decode_params,
    decode_recalibration_params,
    encode_mrcd_params,
    encode_params,
    encode_recalibration_params,
)
from voracious.domain.charts.t2mrcd.revalidation import (
    DEFAULT_MIN_OBSERVATIONS,
    DEFAULT_RELATIVE_CHANGE_THRESHOLD,
    LimitsSnapshot,
    T2MRCDRecalibrationParams,
    T2MRCDRecalibrationReport,
    decide,
)
from voracious.domain.charts.t2mrcd.seeds import (
    SLOT_COVARIANCE_TEST,
    SLOT_MEAN_TEST,
    SLOT_NEW_ROWS,
    SLOT_PHASE1,
    STAGE_INDEX,
    SpawnKey,
)
from voracious.domain.charts.t2mrcd.statistic import t2

__all__ = [
    "BASE_CONSISTENCY_RTOL",
    "BEST_SUBSET_CRITERION_NAME",
    "BOOTSTRAP_LIMIT_NOT_FINITE",
    "BOOTSTRAP_OOB_EMPTY",
    "BOOTSTRAP_REPLICATE_FAILED",
    "CHART_ID",
    "DEFAULT_ALPHA_LIMIT",
    "DEFAULT_MIN_OBSERVATIONS",
    "DEFAULT_N_REPLICATES",
    "DEFAULT_PHASE2_ALPHA_LIMIT",
    "DEFAULT_RELATIVE_CHANGE_THRESHOLD",
    "DEFAULT_STRATEGIES",
    "MC_ERROR_RESAMPLES",
    "MODEL_FORMAT_VERSION",
    "QUANTILE_METHOD",
    "REPORT_FORMAT_VERSION",
    "SLOT_COVARIANCE_TEST",
    "SLOT_MEAN_TEST",
    "SLOT_NEW_ROWS",
    "SLOT_PHASE1",
    "STAGE_INDEX",
    "STATISTIC_REFERENCE",
    "T2MRCD_CLEAN_CRITERION_INVALID",
    "T2MRCD_DECISION_PENDING",
    "T2MRCD_MRCD_ALPHA",
    "T2MRCD_NO_CLEAN_OBSERVATIONS",
    "Aggregations",
    "AnyFormalTestChangeRule",
    "BootstrapLimits",
    "BootstrapOOBSampler",
    "ChangeTestResult",
    "CleanCriterion",
    "ComparisonResult",
    "CovarianceChangeTest",
    "DecisionRule",
    "FrobeniusRelativeChange",
    "LimitAggregation",
    "LimitRegime",
    "LimitsSnapshot",
    "MeanChangeTest",
    "Phase1Stage",
    "PooledQuantile",
    "RelativeChangeMetric",
    "ReplicateContext",
    "ReplicateFailure",
    "ReplicateOutcome",
    "ReplicateSampler",
    "ReplicateTask",
    "SpawnKey",
    "T2MRCDBootstrap",
    "T2MRCDChart",
    "T2MRCDModel",
    "T2MRCDMonitoring",
    "T2MRCDParams",
    "T2MRCDRecalibrationParams",
    "T2MRCDRecalibrationReport",
    "T2MRCDStrategies",
    "any_formal_test_change",
    "best_subset_criterion",
    "bootstrap_oob_sampler",
    "calibrate_limits",
    "calibrate_stage",
    "compare_bases",
    "decide",
    "decode_comparison",
    "decode_limits",
    "decode_model",
    "decode_mrcd_params",
    "decode_params",
    "decode_recalibration_params",
    "decode_report",
    "encode_comparison",
    "encode_limits",
    "encode_model",
    "encode_mrcd_params",
    "encode_params",
    "encode_recalibration_params",
    "encode_report",
    "fit_base",
    "fit_base_mrcd",
    "fit_stage",
    "frobenius_relative_change",
    "pooled_quantile",
    "replicate_tasks",
    "run_replicate",
    "t2",
]
